export * from "./HomePage";
export * from "./PatientAccountPage";
export * from "./PatientAccountAppointments";
export * from "./PatientAccountHelp";
export * from "./PatientAccountPersonalInfo";
export * from "./PatientAccountAdditionalData";
export * from "./PatientAccountPasswordNSecurity";
export * from "./AboutPage";
export * from "./DoctorsPage";
export * from "./DoctorPage";
export * from "./ClinicsPage";
export * from "./ProfilePage";
export * from "./NotFound";
export * from "./Root";
export * from "./PatientPersonalIdentification";
export * from './ClinicInfoPage'
