export * from "./HomePage";
export * from "./Patient-Account-Page";
export * from "./Patient-Account-Appointments";
export * from "./Patient-Account-Help";
export * from "./Patient-Account-Personal-Info";
export * from "./Patient-Account-Additional-Data";
export * from "./Account-Password-N-Security";
export * from "./AboutPage";
export * from "./DoctorsPage";
export * from "./DoctorPage";
export * from "./ClinicsPage";
export * from "./ProfilePage";
export * from "./Not-Found";
export * from "./Root";
export * from './ClinicInfoPage'
export * from "./DoctorAccountPage";
