export * from "./Life";
export * from "./Kyivstar";
export * from "./Vodafone";
export * from "./Instagram";
export * from "./Facebook";
export * from "./Logo-Footer";
export * from "./Telegram-icon";
export * from "./Viber-icon";
export * from "./Logo";
