export * from "./Life";
export * from "./Kyivstar";
export * from "./Vodafon";
export * from "./Instagram";
export * from "./Facebook";
export * from "./Logo.footer";
export * from "./Telegram-icon";
export * from "./Viber-icon";
export * from "./Logo";
